language: php

php:
  - 5.4

before_script:
 - composer install --dev --no-interaction
 - wget https://scrutinizer-ci.com/ocular.phar 

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml


after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml    
    

notifications:
  email:
    - fahim@inbox.com

